name: Install Dependencies
description: |
  Install build dependencies to test and compile Buildome
inputs: {}
runs:
  using: composite
  steps:
    - name: Setup Go
      uses: actions/setup-go@c4a742cab115ed795e34d4513e2cf7d472deb55f
      with:
        go-version-file: src/go.mod
        cache-dependency-path: src/go.sum
        cache: true
    - name: Install Compilers & Formatters
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install --yes bsdutils
        sudo apt-get install --yes build-essential
        sudo apt-get install --yes pkgconf
        sudo apt-get install --yes llvm clang
        sudo apt-get install --yes libelf-dev
