name: Install Dependencies
description: |
  Install build dependencies to test and compile code
inputs: {}
runs:
  using: composite
  steps:
    - name: Setup Go
      uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
      with:
        go-version-file: go.mod
        cache-dependency-path: go.sum
        cache: true
    - name: Install Compilers & Formatters
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install --yes bsdutils
        sudo apt-get install --yes build-essential
        sudo apt-get install --yes pkgconf
        sudo apt-get install --yes llvm clang
        sudo apt-get install --yes libelf-dev
